package com.socketLabs.core.serialization;

public class InjectionResponseDto {

    /// <summary>
    /// The resulting response ErrorCode of the Injection Api send request
    /// </summary>
    public String errorCode;

    /// <summary>
    /// A unique key generated by the Injection API if an unexpected error occurs during the SocketLabsClient send request.
    /// This unique key can be used by SocketLabs support to troubleshoot the issue.
    /// </summary>
    public String transactionReceipt;

    /// <summary>
    /// An array of MessageResultDto objects that contain the status of each message sent.
    /// </summary>
    public MessageResultDto[] messageResults;

    public String getErrorCode() {
        return errorCode;
    }

    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode;
    }

    public String getTransactionReceipt() {
        return transactionReceipt;
    }

    public void setTransactionReceipt(String transactionReceipt) {
        this.transactionReceipt = transactionReceipt;
    }

    public MessageResultDto[] getMessageResults() {
        return messageResults;
    }

    public void setMessageResults(MessageResultDto[] messageResults) {
        this.messageResults = messageResults;
    }
}
